# Metadata for your course

title: Transfer your SVN skill to Git # a name for your Learning Lab course
tagline: If you know how to use SVN, take this course. # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: svn-to-git # the name of the repository when it is created for the learner
  repo: svn-to-git-template # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
  - type: createIssue
    title: Welcome to SVN to Git
    body: welcome.md
    # the type of action, full list at https://lab.github.com/docs/actions/
    # some actions require additional options, those should appear below `type:`
    # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
  - title: Create a branch # the title of the step, shown to the learner in the course progress page
    description: Learn how branches are different in Git by creating a branch # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
    event: create # a list of the actions that will occur when the step is triggered by an event
    actions:
      - type: gate
        left: "%payload.ref_type%"
        operator: ===
        right: branch
        else:
          - type: respond
            with: no-branch-created.md
            data:
              creation: "%payload.ref_type%"
      - type: respond
        with: branch-created.md # the type of action, full list at https://lab.github.com/docs/actions
    # some actions require additional options, those should appear below `type:`
    # you can execute multiple actions in the `before` block
    #
    # - type:
    #   option:
    #
    # - type:
    #   option:
